[dokumentacja](https://pandas.pydata.org/docs/user_guide/index.html)

In [2]:
import pandas as pd
import numpy as np

print("Pandas "+ pd.__version__)
print("Numpy " + np.__version__)

Pandas 2.2.2
Numpy 2.0.2

1. `Series` - pojedyncza kolumna danych w pandas (Można myśleć o niej jak o jednej kolumnie w Excelu)
2. `NaN` - brak danych (Not a Number - ale w pandas używa się go ogólnie jako oznaczenia pustej/brakującej wartości)

In [3]:
data = {
    'Anna' : 25,
    'Jan' : 30,
    'Kasia' : 49
}

s = pd.Series(data)
print(s)

Anna     25
Jan      30
Kasia    49
dtype: int64

In [22]:
s = pd.Series([18, 16, 17, "20", np.nan], index=['k', 'a', 'z', 'b', 'nieznajomy'])
print(s)

print(f"Rozmiar serii: {s.size}")
print(f"Kształt serii: {s.shape}")
print(f"Typ danych w serii: {s.dtype}") # co jeśli w serii będzie więcej niż jeden typ?
print(f"Indexy w serii: {s.index}")
print(f"Wartości w serii: {s.values} ")
print(f"Wartość dla klucza a: {s['a']} ")
print(f"Wartość elemntu na pozycji 1 : {s.iloc[1]}")

k              18
a              16
z              17
b              20
nieznajomy    NaN
dtype: object
Rozmiar serii: 5
Kształt serii: (5,)
Typ danych w serii: object
Indexy w serii: Index(['k', 'a', 'z', 'b', 'nieznajomy'], dtype='object')
Wartości w serii: [18 16 17 '20' nan]
Wartość dla klucza a: 16
Wartość elemntu na pozycji 1 : 16

3. `DataFrame` - cała tabela danych (Można myśleć o nim jak o arkuszu Excela albo tabeli złożonej z wielu kolumn)

In [23]:
import pandas as pd

data = {
    "cena": [15, 20, 17],
    "ilosc" : [40, 60, 50]
}

df = pd.DataFrame(data, index = ["dzień 1", "dzień 2", "dzień 3"])
print(df)

         cena  ilosc
dzień 1    15     40
dzień 2    20     60
dzień 3    17     50

In [24]:
df

         cena  ilosc
dzień 1    15     40
dzień 2    20     60
dzień 3    17     50

In [25]:
print(df.loc["dzień 2"])

cena     20
ilosc    60
Name: dzień 2, dtype: int64

In [26]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, dzień 1 to dzień 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cena    3 non-null      int64
 1   ilosc   3 non-null      int64
dtypes: int64(2)
memory usage: 180.0+ bytes
None

**Mini projekt - analiza danych Gigathonu**

`Założenia` - W analizowanym etapie konkursu brało udział 25 osób które
rozwiązywały zadania. Do zdobycia było maksymalnie 120 punktów. Nie
wszystkie osoby nadesłały prace konkursowe - nie posiadają one przypisanej
punktacji.

[PLIK](https://docs.google.com/spreadsheets/d/1mF209JYrFKZm_ASJ5qcm_BzDSd6JhAz4/edit?gid=442052669#gid=442052669)

Twoim zadaniem jest:
1. Wczytaj dane z pliku Gigathon_Wyniki.xlsx udostępnionego przez
trenera
2. Wyświetl zawartość pliku jako dataframe
3. Wyświetl 5 pierwszych, a następnie 5 ostatnich wpisów w pliku
4. Dodaj kolumnę “Wynik procentowy” która będzie zawierała informację o
wyniku przeliczonym na punkty.
5. Przefiltruj listę uczestników tak, aby zostały tylko osoby które nadesłały
zadania konkursowe
6. Posortuj uczestników od najlepszego wyniku do najsłabszego
7. Dodanie kolumny zakwalifikowany, w której przypisana zostanie
wartość True dla osób które uzyskały ponad 70% możliwych do
uzyskania punktów, reszta osób powinna mieć przypisaną wartość
False
8. Przygotuj zestawienie które pogrupuje uczestników względem
zakwalifikowania się do kolejnego etapu i wieku. Dla każdej grupy zlicz
ile osób mieści się w tym przedziale, jaki był najniższy i największy
wynik w danym przedziale, oraz jaka była średnia i mediana.
9. Rozbij tabelę na dwie mniejsze tabele - zakwalifikowani oraz
niezakwalifikowani. Zapisz je do oddzielnych plików .xlsx

`Niech każdy punkt wykonany zostanie w nowej sekcji kodu`

In [27]:
# 1. Wczytaj dane z pliku Gigathon_Wyniki.xlsx udostępnionego przez trenera
import pandas as pd

df = pd.read_excel("/content/Gigathon_Wyniki.xlsx")

In [28]:
# 2. Wyświetl zawartość pliku jako dataframe
df

         Imię  Wiek  Punktacja
0      Łukasz    18       51.0
1   Magdalena    18       52.0
2    Radosław    15       46.0
3      Patryk    15       52.0
4        Anna    14      110.0
5     Dagmara    16        NaN
6      Tomasz    16      112.0
7    Weronika    17      104.0
8     Nikodem    17       97.0
9      Bartek    14        NaN
10      Jakub    16       61.0
11   Gabriela    16       92.0
12     Hubert    15      120.0
13    Zuzanna    13       70.0
14     Oliwia    14       84.0
15      Filip    16      100.0
16    Ewelina    17       98.0
17   Karolina    14       63.0
18     Xawery    17       39.0
19     Cezary    13        NaN
20        Iga    15       77.0
21    Urszula    14      102.0
22        Jan    17      102.0
23     Michał    15        NaN
24  Katarzyna    18       68.0

In [31]:
# 3. Wyświetl 5 pierwszych,
print(df.head(5))
# a następnie 5 ostatnich wpisów w pliku
print(df.tail(5))

        Imię  Wiek  Punktacja
0     Łukasz    18       51.0
1  Magdalena    18       52.0
2   Radosław    15       46.0
3     Patryk    15       52.0
4       Anna    14      110.0
         Imię  Wiek  Punktacja
20        Iga    15       77.0
21    Urszula    14      102.0
22        Jan    17      102.0
23     Michał    15        NaN
24  Katarzyna    18       68.0

In [33]:
# 4. Dodaj kolumnę “Wynik procentowy” która będzie zawierała informację o wyniku przeliczonym na procenty.
df['Wynik procentowy'] = df['Punktacja']/120 * 100
df

         Imię  Wiek  Punktacja  Wynik procentowy
0      Łukasz    18       51.0         42.500000
1   Magdalena    18       52.0         43.333333
2    Radosław    15       46.0         38.333333
3      Patryk    15       52.0         43.333333
4        Anna    14      110.0         91.666667
5     Dagmara    16        NaN               NaN
6      Tomasz    16      112.0         93.333333
7    Weronika    17      104.0         86.666667
8     Nikodem    17       97.0         80.833333
9      Bartek    14        NaN               NaN
10      Jakub    16       61.0         50.833333
11   Gabriela    16       92.0         76.666667
12     Hubert    15      120.0        100.000000
13    Zuzanna    13       70.0         58.333333
14     Oliwia    14       84.0         70.000000
15      Filip    16      100.0         83.333333
16    Ewelina    17       98.0         81.666667
17   Karolina    14       63.0         52.500000
18     Xawery    17       39.0         32.500000
19     Cezary    13        NaN               NaN
20        Iga    15       77.0         64.166667
21    Urszula    14      102.0         85.000000
22        Jan    17      102.0         85.000000
23     Michał    15        NaN               NaN
24  Katarzyna    18       68.0         56.666667

In [34]:
# 5. Przefiltruj listę uczestników tak,
# aby zostały tylko osoby które nadesłały zadania konkursowe

# Do usunięcia rekordów z wartością NaN służy metoda .dropna().
# Parametr inplace informuje że usuwamy dane z oryginalnego
# dataframe, domyślnie metoda zwraca kopię dataframe z usuniętymi
# rekordami.

df.dropna(inplace=True)
df

         Imię  Wiek  Punktacja  Wynik procentowy
0      Łukasz    18       51.0         42.500000
1   Magdalena    18       52.0         43.333333
2    Radosław    15       46.0         38.333333
3      Patryk    15       52.0         43.333333
4        Anna    14      110.0         91.666667
6      Tomasz    16      112.0         93.333333
7    Weronika    17      104.0         86.666667
8     Nikodem    17       97.0         80.833333
10      Jakub    16       61.0         50.833333
11   Gabriela    16       92.0         76.666667
12     Hubert    15      120.0        100.000000
13    Zuzanna    13       70.0         58.333333
14     Oliwia    14       84.0         70.000000
15      Filip    16      100.0         83.333333
16    Ewelina    17       98.0         81.666667
17   Karolina    14       63.0         52.500000
18     Xawery    17       39.0         32.500000
20        Iga    15       77.0         64.166667
21    Urszula    14      102.0         85.000000
22        Jan    17      102.0         85.000000
24  Katarzyna    18       68.0         56.666667

In [35]:
# 6. Posortuj uczestników od najlepszego wyniku do najsłabszego

# Do sortowania wartości służy metoda .sort_values().
# Parametry:
# 'by' - według której kolumny odbywa się sortowanie,
# 'ascending' - kolejność sortowania (rosnąca lub malejąca).

df.sort_values(by="Punktacja", ascending=False, inplace=True)
df

         Imię  Wiek  Punktacja  Wynik procentowy
12     Hubert    15      120.0        100.000000
6      Tomasz    16      112.0         93.333333
4        Anna    14      110.0         91.666667
7    Weronika    17      104.0         86.666667
22        Jan    17      102.0         85.000000
21    Urszula    14      102.0         85.000000
15      Filip    16      100.0         83.333333
16    Ewelina    17       98.0         81.666667
8     Nikodem    17       97.0         80.833333
11   Gabriela    16       92.0         76.666667
14     Oliwia    14       84.0         70.000000
20        Iga    15       77.0         64.166667
13    Zuzanna    13       70.0         58.333333
24  Katarzyna    18       68.0         56.666667
17   Karolina    14       63.0         52.500000
10      Jakub    16       61.0         50.833333
3      Patryk    15       52.0         43.333333
1   Magdalena    18       52.0         43.333333
0      Łukasz    18       51.0         42.500000
2    Radosław    15       46.0         38.333333
18     Xawery    17       39.0         32.500000

In [36]:
# 7. Dodanie kolumny zakwalifikowany,
# w której przypisana zostanie wartość True dla osób które uzyskały
# ponad 70% możliwych do uzyskania punktów,
# reszta osób powinna mieć przypisaną wartość False

df['Zakwalifikowany'] = df['Wynik procentowy'] > 70
df

         Imię  Wiek  Punktacja  Wynik procentowy  Zakwalifikowany
12     Hubert    15      120.0        100.000000             True
6      Tomasz    16      112.0         93.333333             True
4        Anna    14      110.0         91.666667             True
7    Weronika    17      104.0         86.666667             True
22        Jan    17      102.0         85.000000             True
21    Urszula    14      102.0         85.000000             True
15      Filip    16      100.0         83.333333             True
16    Ewelina    17       98.0         81.666667             True
8     Nikodem    17       97.0         80.833333             True
11   Gabriela    16       92.0         76.666667             True
14     Oliwia    14       84.0         70.000000            False
20        Iga    15       77.0         64.166667            False
13    Zuzanna    13       70.0         58.333333            False
24  Katarzyna    18       68.0         56.666667            False
17   Karolina    14       63.0         52.500000            False
10      Jakub    16       61.0         50.833333            False
3      Patryk    15       52.0         43.333333            False
1   Magdalena    18       52.0         43.333333            False
0      Łukasz    18       51.0         42.500000            False
2    Radosław    15       46.0         38.333333            False
18     Xawery    17       39.0         32.500000            False

In [39]:
# 8. Przygotuj zestawienie które pogrupuje uczestników
# względem zakwalifikowania się do kolejnego etapu i wieku.
# Dla każdej grupy zlicz ile osób mieści się w tym przedziale,
# jaki był najniższy i największy wynik w danym przedziale,
# oraz jaka była średnia i mediana.

df.groupby(["Zakwalifikowany", "Wiek"])[["Punktacja", "Wynik procentowy"]].agg(["count", "min", "max", "mean", "median"])

                     Punktacja                                   \
                         count    min    max        mean median
Zakwalifikowany Wiek
False           13           1   70.0   70.0   70.000000   70.0
                14           2   63.0   84.0   73.500000   73.5
                15           3   46.0   77.0   58.333333   52.0
                16           1   61.0   61.0   61.000000   61.0
                17           1   39.0   39.0   39.000000   39.0
                18           3   51.0   68.0   57.000000   52.0
True            14           2  102.0  110.0  106.000000  106.0
                15           1  120.0  120.0  120.000000  120.0
                16           3   92.0  112.0  101.333333  100.0
                17           4   97.0  104.0  100.250000  100.0

                     Wynik procentowy                                      \
                                count         min         max        mean
Zakwalifikowany Wiek
False           13                  1   58.333333   58.333333   58.333333
                14                  2   52.500000   70.000000   61.250000
                15                  3   38.333333   64.166667   48.611111
                16                  1   50.833333   50.833333   50.833333
                17                  1   32.500000   32.500000   32.500000
                18                  3   42.500000   56.666667   47.500000
True            14                  2   85.000000   91.666667   88.333333
                15                  1  100.000000  100.000000  100.000000
                16                  3   76.666667   93.333333   84.444444
                17                  4   80.833333   86.666667   83.541667


                          median
Zakwalifikowany Wiek
False           13     58.333333
                14     61.250000
                15     43.333333
                16     50.833333
                17     32.500000
                18     43.333333
True            14     88.333333
                15    100.000000
                16     83.333333
                17     83.333333

In [44]:
# 9. Rozbij tabelę na dwie mniejsze tabele
# - zakwalifikowani
# -niezakwalifikowani
# Zapisz je do oddzielnych plików .xlsx

df_zak = df[df["Zakwalifikowany"]]
df_zak.drop("Zakwalifikowany", axis=1, inplace=True)
df_zak.to_excel("zakwalifikowani.xlsx")
df_zak

/tmp/ipykernel_1370/2835473773.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_zak.drop("Zakwalifikowany", axis=1, inplace=True)

        Imię  Wiek  Punktacja  Wynik procentowy
12    Hubert    15      120.0        100.000000
6     Tomasz    16      112.0         93.333333
4       Anna    14      110.0         91.666667
7   Weronika    17      104.0         86.666667
22       Jan    17      102.0         85.000000
21   Urszula    14      102.0         85.000000
15     Filip    16      100.0         83.333333
16   Ewelina    17       98.0         81.666667
8    Nikodem    17       97.0         80.833333
11  Gabriela    16       92.0         76.666667

In [45]:
df_niezak = df[~df["Zakwalifikowany"]]
df_niezak.drop("Zakwalifikowany", axis=1, inplace=True)
df_niezak.to_excel("niezakwalifikowani.xlsx")
df_niezak

/tmp/ipykernel_1370/795512046.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_niezak.drop("Zakwalifikowany", axis=1, inplace=True)

         Imię  Wiek  Punktacja  Wynik procentowy
14     Oliwia    14       84.0         70.000000
20        Iga    15       77.0         64.166667
13    Zuzanna    13       70.0         58.333333
24  Katarzyna    18       68.0         56.666667
17   Karolina    14       63.0         52.500000
10      Jakub    16       61.0         50.833333
3      Patryk    15       52.0         43.333333
1   Magdalena    18       52.0         43.333333
0      Łukasz    18       51.0         42.500000
2    Radosław    15       46.0         38.333333
18     Xawery    17       39.0         32.500000

## **ZADANIE DODATKOWE**

[Pokemon.csv](https://drive.google.com/file/d/1Inds2JLPhJeSEVXn91kgpoSQ9p3EM6FE/view)

Plik CSV (Comma-Separated Values) to format tekstowy używany do
przechowywania danych tabelarycznych, gdzie wartości są oddzielone
przecinkami lub innymi separatorami (np. średnikami). Każdy wiersz
reprezentuje jeden rekord, a kolumny odpowiadają różnym atrybutom, co
umożliwia łatwe przetwarzanie w programach takich jak Excel, Pandas czy bazy danych.

Zadania:
1. Wczytaj plik “Pokemon.csv” i wyświetl pierwsze 10 rekordów
2. Wyświetl liczbę unikalnych wartości w kolumnie “Type 1” *
3. Policz ile jest pokemonów legendarnych
4. Sprawdź ile pokemonów nie posiada Typu 2
5. Znajdź pokemony z najwyższą wartością Total
6. Zlicz pokemony z każdej generacji (Generation) i narysuj wykres kołowy
prezentujący ich liczbę
7. Znajdź wszystkie pokemony, których główny typ (Type 1) to ogień
8. Wyświetl Pokémony, które mają HP większe niż 100
9. Wyświetl legendarne pokemony z Speed powyżej 120
10. Wyświetl pokemony które mają zarówno Attack > 100, jak i Defense < 50
11. Znajdź średnią wartość HP dla każdego z typów pokemonów
12. Oblicz średnią moc (Total) dla pokemonów legendarnych i
nie-legendarnych
13. Oblicz średnią prędkość (Speed) dla każdej z generacji

### Miniściąga

`pd.read_csv()` → wczytaj plik CSV  
`df.head(10)` → pokaż pierwsze 10 rekordów  
`df["Type 1"].nunique()` → policz liczbę różnych wartości  
`df["Type 2"].isna().sum()` → policz puste pola  
`df["Legendary"].sum()` → policz wartości `True`  
`df["Total"].max()` → znajdź największą wartość  
`df[df["kolumna"] == wartość]` → filtruj dane  
`df[df["kolumna"] > wartość]` → filtruj po liczbach  
`df[(warunek1) & (warunek2)]` → dwa warunki naraz, czyli „i”  
`df[(warunek1) | (warunek2)]` → dwa warunki naraz, czyli „lub”  
`df["Generation"].value_counts()` → policz wystąpienia wartości  
`df.groupby("Type 1")["HP"].mean()` → policz średnią w grupach  
`df["Generation"].value_counts().plot(kind="pie", autopct="%1.1f%%")` → wykres kołowy  
`plt.show()` → pokaż wykres

In [46]:
import pandas as pd
import matplotlib.pyplot as pls

In [47]:
# 1. Wczytaj plik “Pokemon.csv” i wyświetl pierwsze 10 rekordów
df1 = pd.read_csv("/content/Pokemon.csv")
df1.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

In [48]:
# 2. Wyświetl liczbę unikalnych wartości w kolumnie “Type 1” *
df1['Type 1'].nunique()

18